### PR TITLE
Code Refactor 

### PR DESCRIPTION
**Pull request by Josephdias92**
changed image default from null to array,changed all the strin
g from double quotes to single quotes, removed unnecessary if statements and removed multiple jquery dom calls to one call by creating a reference

### CODE REVIEW

**Comment by smirolo** [comment]
Thank you @Josephdias92. It all looks great.

Just a question: Why did you change the double quotes into single quotes?
eslint complains about single quotes. That's why we used double quotes throughout :).

**Comment by Josephdias92** [comment]
hello @smirolo 
Im following google style guide rules for eslint, which uses single quote for strings.

**Comment by smirolo** [comment]
OK. Here for reference for anyone else reading: [Google Javascript style guidelines](https://google.github.io/styleguide/javascriptguide.xml#Strings).
I installed [eslint-config-google](https://github.com/google/eslint-config-google) v0.5.0 and ran eslint v2.9.0 on the refactor-code branch for this pull request. The number of "problems" is down to 35 from 261 on master. Nice!

@Josephdias92, would you mind completing the refactor to remove the last problems?

I will then add a section to the README.md file that this project follows Google Javascript style guidelines for future contributors.

Thank you so much!

**Comment by Josephdias92** [comment]
hello @smirolo 
i just finished fixing all eslint errors :)

**Comment by smirolo** [comment]
confirmed. Awesome work. Thank you!

**Pull request merged**
