### PR TITLE
Added pen tool

### PR DESCRIPTION
**Pull request by paulJordaan**
Hi, 

I've added a pen tool to your  plugin. I've also updated the plugin to use two canvas elements. This allows one canvas to be used for drawing new elements while the base canvas stores all previously drawn elements. By doing this I eliminate the need to redraw all elements on each mouse move event.

### CODE REVIEW

**Comment by StephaneRob** [comment]
Hi,
Can you remove all bower components from the pull request?
Now they are in ```.gitignore```, we wouldn't want them anymore in the repo.
Thanks

**Comment by paulJordaan** [comment]
Hi,

Sorry about that, I'm quite new to this. 
I cleaned up my branch and updated the README.
You'll see the plugin now needs to be initialized on a div instead of a canvas.

I hope everything is fine now, let me know if I need to change anything.

Cheers

**Comment by smirolo** [comment]
Thanks Paul. I reviewed the pull request and it looks good. Testing tomorrow and merging afterwards.

**Comment by smirolo** [comment]
Hi @paulJordaan, I merged your pull request manually such as to remove the history of ignored files that made it to the repo at one point. Here the commands I used:

    $ git checkout -b paulJordaan-master master
    $ git pull https://github.com/paulJordaan/djaodjin-annotate.git master
    $ git rebase -i HEAD~5
    pick 9f2301f Added pen tool
    -pick 43a247a Added bower_components to .gitignore
    -pick f2aef45 Cleanup bower files
    -pick abc3475 Update .gitignore
    -pick 77e07ed Updated README
    +squash 43a247a Added bower_components to .gitignore
    +squash f2aef45 Cleanup bower files
    +squash abc3475 Update .gitignore
    +squash 77e07ed Updated README
    ... edit conflicts ...
    $ git add .gitignore
    $ git rebase --continue
    $ git checkout master
    $ git merge --no-ff paulJordaan-master
    $ git push origin master

Because I rewrote history, you might have some issues if you try to pull origin master directly into your fork.  None-the-less, your updates are now available as a [single commit](https://github.com/djaodjin/djaodjin-annotate/commit/29c4f78dfeeb5a7fe04c7a192901828ab258469c) with you as the Author.

Thank you so much!

**Pull request closed without merging**
