### PR TITLE
adding circle annotation

### PR DESCRIPTION
**Pull request by rob-in**
Hi,

I added the circle annotation to the existing library.
Please verify and merge it to the master code base.

### CODE REVIEW

**Comment by StephaneRob** [comment]
Thanks @rob-in, I reviewed the pull request and there is only one thing. It seems that the circle (ellipse) path is not closed.

I think need to add ```context.closePath();``` before ```context.stroke();``` on ```drawCircle()```.

**Comment by rob-in** [comment]
Okay,,,, 
But dont understand the reason behind it ?

**Comment by rob-in** [comment]
I mean when we are drwign line with "pen" option we are not doing it..

**Comment by StephaneRob** [comment]
Here is a screenshot, the circle need to be closed.
screen shot 2015-08-28 at 11 12 20

**Comment by rob-in** [comment]
Ahh..
got it..
Thanks....

**Comment by rob-in** [comment]
Done.. Please merge to master..

**Comment by smirolo** [comment]
Thanks @rob-in

**Pull request merged**
